import { ulid } from './ids'
import { db } from './schema'
import type { Cefr, Entry, PartOfSpeech, Translation } from './types'

// Loads the real Swedish seed (data → public/seed-sv.json, generated by scripts/seed) into
// Dexie on first launch. Replaces the old dev sample. (SPEC §9, §13)

interface SeedEntry {
  lemma: string
  pos: PartOfSpeech
  cefr: Cefr
  gender?: string
  ipa?: string
  inflections?: Record<string, string>
  subDefinitions?: string[]
  examples?: string[]
  translation: string
}

/** True when the seed was actually imported (first launch), false when the DB was already populated. */
export async function loadSeedIfEmpty(): Promise<boolean> {
  if ((await db.entries.count()) > 0) {
    await ensureProfile()
    return false
  }

  const res = await fetch(`${import.meta.env.BASE_URL}seed-sv.json`)
  if (!res.ok) throw new Error(`seed HTTP ${res.status}`)
  const seed = (await res.json()) as { version: string; entries: SeedEntry[] }

  const now = Date.now()
  const entries: Entry[] = []
  const translations: Translation[] = []
  for (const s of seed.entries) {
    const target: Entry = {
      id: ulid(),
      lang: 'sv',
      lemma: s.lemma,
      pos: s.pos,
      features: s.gender ? { gender: s.gender } : {},
      inflections: s.inflections ?? {},
      pronunciation: s.ipa ? { ipa: s.ipa, ipaSource: 'wiktionary' } : {},
      cefr: s.cefr,
      subDefinitions: s.subDefinitions,
      examples: s.examples,
      source: 'seed',
      seedVersion: seed.version,
      study: 'auto',
      createdAt: now,
      updatedAt: now,
    }
    const native: Entry = {
      id: ulid(),
      lang: 'en',
      lemma: s.translation,
      pos: s.pos,
      features: {},
      inflections: {},
      pronunciation: {},
      source: 'seed',
      seedVersion: seed.version,
      study: 'auto',
      createdAt: now,
      updatedAt: now,
    }
    entries.push(target, native)
    translations.push({ id: ulid(), targetEntryId: target.id, nativeEntryId: native.id, source: 'seed', createdAt: now })
  }

  await db.transaction('rw', db.entries, db.translations, async () => {
    await db.entries.bulkAdd(entries)
    await db.translations.bulkAdd(translations)
  })
  await ensureProfile()
  return true
}

/** Ensure a single active profile exists (sv→en, A1) until onboarding is built. */
async function ensureProfile(): Promise<void> {
  if (await db.profiles.filter((p) => p.active).first()) return
  const now = Date.now()
  await db.profiles.add({
    id: ulid(),
    learnerLang: 'en',
    targetLang: 'sv',
    claimedLevel: 'A1',
    dailyLimits: { newPerDay: 20, practicePerDay: 200 },
    active: true,
    createdAt: now,
    updatedAt: now,
  })
}
