// Chunk ambiguous English concepts into batches for the gloss-curator subagent (layer 50), the §12
// re-run of the sense pass over an EXPANDED candidate set: every English phrase produced by >=2
// Swedish MEANING-SLOTS — counting both primary translations AND promoted altMeanings (which the old
// primary-only grouping could never reach). The agent partitions each concept's producers into senses
// and writes a short distinguishing gloss per sense (empty for a one-sense synonym group).
//
// Selection is the REPAIR SET, not a full sweep — gloss authority stays single and the 1,865 already-
// useful glosses are preserved by RECONCILE (seed:reconcile re-stamps the untouched concepts). A
// concept is batched only when curation must actually change something:
//   • it contains a promoted altMeaning slot (the mechanism gap — needs partitioning + a gloss), or
//   • it is NEW (an English phrase that reaches >=2 producers only via a promoted slot), or
//   • it is multi-sense today with a member whose gloss is EMPTY or ECHOES its phrase (the 110 + the
//     article/POS near-echoes the new reducer rule would otherwise blank into fresh gaps).
// SEED_BATCH_ALL=1 forces every ambiguous concept (a full re-curation).
//
// The concept (english + its producer set) is the FROZEN input; its `inputHash` matches the senses
// layer's staleness hash, so an echoed answer clears staleness. `currentGloss` (primary: the concept's
// prior sense gloss; promoted: the split pass's candidate gloss) + subDefinitions/examples/wik are
// supplementary CONTEXT (not hashed) so the agent can preserve good glosses and judge senses.
// Output: data/scratch/sv/gloss-batches/<n>.json
// Run: node scripts/seed/batch-gloss.mjs   (after seed:apply + seed:stale)
import { existsSync } from 'node:fs'
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { assemble, layerDir, loadManifest, normTr, sameText, SCRATCH_DIR, shortHash } from '../lib/layers.mjs'

const BATCH_DIR = `${SCRATCH_DIR}/gloss-batches`
const WIK = `${SCRATCH_DIR}/wik.json` // context only (not part of inputHash); regenerated by seed:fetch
const BATCH_SIZE = 60
// Local date, so a run file sorts AFTER same-UTC-day earlier runs (import/migration/reconcile) and
// wins the compile's newest-per-concept fold. The `gloss-` infix keeps the ledger legible.
const now = new Date()
const DATE = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`
const CEFR_RANK = { A1: 1, A2: 2, B1: 3, B2: 4, C1: 5, C2: 6 }

const memberId = (m) => (typeof m === 'number' ? m : m.kellyId)
const memberKey = (m) => (typeof m === 'number' ? 0 : (m.meaningKey ?? 0))

function wikSenses(wik, lemma, pos, gender) {
  const all = wik[lemma] ?? []
  const exact = all.filter((w) => w.pos === pos)
  const genderMatch = pos === 'noun' && gender ? exact.filter((w) => w.gender === gender) : []
  const preferred = genderMatch.length ? genderMatch : exact
  const wiks = preferred.length ? preferred : all
  return [...new Set(wiks.flatMap((w) => w.glosses ?? []))]
}

async function main() {
  const manifest = await loadManifest()
  const layer = manifest.find((l) => l.kind === 'senses')
  const splitLayer = manifest.find((l) => l.kind === 'split')
  const { finalEntries, concepts } = await assemble(manifest, { upToExclusive: layer.id })
  const byKelly = new Map(finalEntries.map((e) => [e.kellyId, e]))
  const wik = existsSync(WIK) ? JSON.parse(await readFile(WIK, 'utf-8')) : {}
  if (!existsSync(WIK)) console.warn(`warning: ${WIK} not found — batching without Wiktionary context (run pnpm seed:fetch)`)

  // Prior gloss decisions: the concept partition we're improving. Map "kellyId:meaningKey" → the sense
  // gloss that slot currently carries (its currentGloss), and english → the prior concept (for the
  // defect test). Members may be legacy bare ints (primary, meaningKey 0) or {kellyId, meaningKey}.
  const dir = layerDir(layer)
  const priorDecisions = existsSync(`${dir}/decisions.json`) ? JSON.parse(await readFile(`${dir}/decisions.json`, 'utf-8')) : []
  const priorByEnglish = new Map(priorDecisions.map((c) => [c.english, c]))
  const priorGloss = new Map()
  for (const c of priorDecisions)
    for (const s of c.senses ?? [])
      for (const m of s.members ?? []) priorGloss.set(`${memberId(m)}:${memberKey(m)}`, (s.gloss ?? '').trim())

  // The split pass's candidate gloss for a promoted meaning (context the sense pass should not discard).
  const splitDecisions = existsSync(`${layerDir(splitLayer)}/decisions.json`) ? JSON.parse(await readFile(`${layerDir(splitLayer)}/decisions.json`, 'utf-8')) : []
  const splitGloss = new Map()
  for (const d of splitDecisions) for (const m of d.altMeanings ?? []) if (m.gloss) splitGloss.set(`${d.kellyId}:${normTr(m.translation)}`, m.gloss)

  const all = process.env.SEED_BATCH_ALL === '1'
  const phraseOf = (m) => (m.promoted ? byKelly.get(m.kellyId)?.altMeanings?.find((a) => a.key === m.meaningKey)?.translation : byKelly.get(m.kellyId)?.translation) ?? ''

  // A prior multi-sense concept whose stored partition contains an empty or echoing gloss — the new
  // reducer rule would blank the echo into a fresh gap, so it must be re-curated, not reconciled.
  const hasDefect = (english) => {
    const prior = priorByEnglish.get(english)
    if (!prior || (prior.senses ?? []).length < 2) return false
    for (const s of prior.senses) {
      const g = (s.gloss ?? '').trim()
      for (const m of s.members ?? []) {
        const phrase = byKelly.get(memberId(m))?.translation ?? ''
        if (g === '' || sameText(g, phrase)) return true
      }
    }
    return false
  }

  const items = []
  for (const c of concepts) {
    const needs = all || c.members.some((m) => m.promoted) || !priorByEnglish.has(c.english) || hasDefect(c.english)
    if (!needs) continue // untouched — seed:reconcile re-stamps it, preserving its glosses
    const producers = c.members.map((m) => {
      const e = byKelly.get(m.kellyId)
      const translation = phraseOf(m)
      const currentGloss = m.promoted ? (splitGloss.get(`${m.kellyId}:${normTr(translation)}`) ?? '') : (priorGloss.get(`${m.kellyId}:0`) ?? '')
      return {
        kellyId: m.kellyId,
        meaningKey: m.meaningKey,
        lemma: m.lemma,
        pos: m.pos,
        cefr: e?.cefr,
        promoted: m.promoted,
        translation,
        currentGloss,
        ...(e?.subDefinitions?.length ? { subDefinitions: e.subDefinitions } : {}),
        ...(!m.promoted && e?.examples?.length ? { examples: e.examples.slice(0, 2) } : {}),
        wiktionarySenses: wikSenses(wik, m.lemma, m.pos, e?.gender),
      }
    })
    items.push({ english: c.english, producers, inputHash: shortHash(c) })
  }
  // Lowest level first — beginners matter most, so curate the phrases they meet earliest with care.
  items.sort((a, b) => Math.min(...a.producers.map((p) => CEFR_RANK[p.cefr] ?? 9)) - Math.min(...b.producers.map((p) => CEFR_RANK[p.cefr] ?? 9)) || a.english.localeCompare(b.english, 'sv'))

  if (items.length === 0) {
    console.log('nothing to batch (no promoted / new / defective concepts — run with SEED_BATCH_ALL=1 for a full pass)')
    return
  }
  if (existsSync(BATCH_DIR)) for (const f of await readdir(BATCH_DIR)) await rm(`${BATCH_DIR}/${f}`)
  await mkdir(BATCH_DIR, { recursive: true })
  let n = 0
  for (let i = 0; i < items.length; i += BATCH_SIZE) {
    await writeFile(`${BATCH_DIR}/${DATE}-gloss-${String(n).padStart(3, '0')}.json`, JSON.stringify(items.slice(i, i + BATCH_SIZE), null, 2))
    n++
  }
  console.log(`wrote ${n} gloss batches (${items.length} concepts${all ? ', full pass' : ', repair set'}, size ${BATCH_SIZE}) → ${BATCH_DIR}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
