// Chunk candidate words into batches for the split-curator subagent (layer 45), which decides which
// of a word's distinct meanings deserve their own production card (altMeanings) vs. stay reference-only.
//
// The curator sees a STABLE, FROZEN input — the word as resolved from base + the layers below 45
// (cleaner/pos/subdef/translation), so it partitions the already-curated meaning list. Each item
// carries its `inputHash`; the agent echoes it back so staleness is mechanical.
//
// Candidate set (design §8): words that *could* be multi-meaning — those with a meaning list, plus
// those whose main translation is SEMICOLON-joined (the "two co-equal meanings" case, e.g. "duty; tax").
// Comma-joined translations are excluded: a comma marks synonyms of ONE sense ("big, large"), not a
// second meaning to split off. Most candidates still return "no split needed". Selection: by default
// only STALE + NEW (never curated) candidates; SEED_BATCH_ALL=1 forces a full pass over all candidates.
// Output: data/scratch/sv/split-batches/<n>.json
// Run: node scripts/seed/batch-split.mjs   (after seed:apply + seed:stale)
import { existsSync } from 'node:fs'
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { assemble, layerDir, loadManifest, SCRATCH_DIR, shortHash, wordFrozenInput } from './lib/layers.mjs'

const BATCH_DIR = `${SCRATCH_DIR}/split-batches`
const WIK = `${SCRATCH_DIR}/wik.json` // context only (not part of inputHash); regenerated by seed:fetch
const BATCH_SIZE = 100
const DATE = new Date().toISOString().slice(0, 10) // dated so compile's newest-per-word wins
const CEFR_RANK = { A1: 1, A2: 2, B1: 3, B2: 4, C1: 5, C2: 6 }

// A word is a split candidate if it carries a meaning list, or its primary is SEMICOLON-joined (two
// co-equal senses hiding in one headline, e.g. "duty; tax"). Comma-joined translations are synonyms of
// one sense, not a split, so they're excluded. Single clean translations are skipped untouched.
const isCandidate = (e) => (e.subDefinitions?.length ?? 0) > 0 || /;/.test(e.translation ?? '')

function wikSenses(wik, lemma, pos, gender) {
  const all = wik[lemma] ?? []
  const exact = all.filter((w) => w.pos === pos)
  const genderMatch = pos === 'noun' && gender ? exact.filter((w) => w.gender === gender) : []
  const preferred = genderMatch.length ? genderMatch : exact
  const wiks = preferred.length ? preferred : all
  return [...new Set(wiks.flatMap((w) => w.glosses ?? []))]
}

async function main() {
  const manifest = await loadManifest()
  const layer = manifest.find((l) => l.kind === 'split')
  const { finalEntries } = await assemble(manifest, { upToExclusive: layer.id })
  const wik = existsSync(WIK) ? JSON.parse(await readFile(WIK, 'utf-8')) : {}
  if (!existsSync(WIK)) console.warn(`warning: ${WIK} not found — batching without Wiktionary context (run pnpm seed:fetch)`)

  const dir = layerDir(layer)
  const curated = new Set(existsSync(`${dir}/decisions.json`) ? JSON.parse(await readFile(`${dir}/decisions.json`, 'utf-8')).map((d) => d.kellyId) : [])
  const staleKeys = new Set(existsSync(`${dir}/stale.json`) ? JSON.parse(await readFile(`${dir}/stale.json`, 'utf-8')).map((s) => s.key) : [])
  const all = process.env.SEED_BATCH_ALL === '1'

  const items = finalEntries
    .filter(isCandidate)
    .filter((e) => all || staleKeys.has(e.kellyId) || curated.has(e.kellyId) === false)
    .map((e) => ({
      kellyId: e.kellyId,
      lemma: e.lemma,
      pos: e.pos,
      ...(e.gender ? { gender: e.gender } : {}),
      cefr: e.cefr,
      translation: e.translation,
      ...(e.subDefinitions?.length ? { subDefinitions: e.subDefinitions } : {}),
      ...(e.examples?.length ? { examples: e.examples } : {}),
      wiktionarySenses: wikSenses(wik, e.lemma, e.pos, e.gender),
      inputHash: shortHash(wordFrozenInput(e)), // echo back unchanged in the answer
    }))
    .sort((a, b) => (CEFR_RANK[a.cefr] ?? 9) - (CEFR_RANK[b.cefr] ?? 9) || a.lemma.localeCompare(b.lemma, 'sv'))

  if (items.length === 0) {
    console.log('nothing to batch (no stale or new candidates — run with SEED_BATCH_ALL=1 for a full pass)')
    return
  }
  if (existsSync(BATCH_DIR)) for (const f of await readdir(BATCH_DIR)) await rm(`${BATCH_DIR}/${f}`)
  await mkdir(BATCH_DIR, { recursive: true })
  let n = 0
  for (let i = 0; i < items.length; i += BATCH_SIZE) {
    await writeFile(`${BATCH_DIR}/${DATE}-${String(n).padStart(3, '0')}.json`, JSON.stringify(items.slice(i, i + BATCH_SIZE), null, 2))
    n++
  }
  console.log(`wrote ${n} split batches (${items.length} candidates${all ? ', full pass' : ', stale+new'}, size ${BATCH_SIZE}) → ${BATCH_DIR}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
